version: "3"

services:
  nano_siem:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # user: 1000:1000
    env_file:
      - .env
    volumes:
      - $PWD/../nano_siem_data/access.log:/var/log/traefik_access.log
      - $PWD/../nano_siem_data/GeoIP.conf:/etc/GeoIP.conf
      - $PWD/crontab.log:/home/NanoSiem/.nano_siem/crontab.log
      - /:/mnt/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  nano_siem_db:
    image: mariadb:10.10
    user: 1000:1000
    volumes:
      - $PWD/../nano_siem_data/database:/var/lib/mysql
    command: --innodb-buffer-pool-size=5G --key-buffer-size=1G
    environment:
      - MARIADB_USER=NanoSiem
      - MARIADB_DATABASE=NanoSiem
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 127.0.0.1:3306:3306
