# Generated by Django 4.1.3 on 2022-11-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(db_index=True, max_length=40)),
                ('log_position', models.BigIntegerField()),
                ('log_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('requested_service', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('asn', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('user', models.TextField()),
                ('event', models.TextField()),
                ('message', models.TextField()),
                ('http_status', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('content_size', models.IntegerField()),
                ('is_tor', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service')),
            ],
        ),
    ]
