# Generated by Django 4.1.3 on 2022-11-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelog',
            old_name='asn',
            new_name='autonomous_system_organization',
        ),
        migrations.RenameField(
            model_name='servicelog',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='servicelog',
            old_name='country',
            new_name='country_name',
        ),
    ]
