# Generated by Django 4.1.3 on 2023-02-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diskservicelog",
            name="free_space",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="diskservicelog",
            name="used_space",
            field=models.BigIntegerField(default=0),
        ),
    ]
