# Generated by Django 4.1.3 on 2022-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_service_modification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
