# Generated by Django 4.1.3 on 2022-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_service_modification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='content_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='http_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
