# Generated by Django 4.1.3 on 2022-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_servicelog_content_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
