# Generated by Django 4.1.3 on 2022-11-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_service_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='latitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='longitude',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
