# Generated by Django 4.1.3 on 2022-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_servicelog_content_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='autonomous_system_organization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='city_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='country_name',
            field=models.TextField(null=True),
        ),
    ]
