# Generated by Django 4.1.3 on 2022-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_servicelog_ids_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelog",
            name="is_tor",
            field=models.BooleanField(db_index=True),
        ),
    ]
