# Generated by Django 4.1.3 on 2022-12-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_servicelog_is_tor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLogFail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("message", models.TextField()),
                ("seen", models.BooleanField(db_index=True)),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.service"
                    ),
                ),
            ],
        ),
    ]
