# Generated by Django 4.1.3 on 2022-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_servicelogfail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelogfail",
            name="seen",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
