# Generated by Django 4.1.3 on 2022-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_servicelogfail_autonomous_system_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelog",
            name="event",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="request_method",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="requested_service",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="user",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="user_agent",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="ServiceLogFail",
        ),
    ]
