# Generated by Django 4.1.3 on 2022-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_alter_servicelog_event_alter_servicelog_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelog",
            name="ids_score",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
