# Generated by Django 4.1.3 on 2023-01-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_alter_servicelog_ids_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverwatchService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("type", models.CharField(db_index=True, max_length=10)),
                ("available", models.BooleanField()),
                ("modification_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OverwatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True, db_index=True)),
                ("latency", models.FloatField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.overwatchservice",
                    ),
                ),
            ],
        ),
    ]
