# Generated by Django 4.1.3 on 2023-01-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_overwatchservice_overwatchlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overwatchlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
