# Generated by Django 4.1.3 on 2023-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_alter_overwatchlog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="overwatchservice",
            name="host",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="overwatchservice",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="overwatchservice",
            name="port",
            field=models.IntegerField(default=0),
        ),
    ]
