# Generated by Django 4.1.3 on 2023-01-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_overwatchservice_host_overwatchservice_notified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overwatchservice",
            old_name="notified",
            new_name="notify",
        ),
    ]
