# Generated by Django 4.1.3 on 2023-01-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_rename_notified_overwatchservice_notify"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overwatchservice",
            old_name="notify",
            new_name="notified",
        ),
    ]
