# Generated by Django 4.1.3 on 2023-02-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("type", models.CharField(db_index=True, max_length=40)),
                ("log_position", models.BigIntegerField()),
                ("log_path", models.TextField()),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("running", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("requested_service", models.TextField(null=True)),
                ("ip", models.GenericIPAddressField()),
                ("longitude", models.FloatField(db_index=True, null=True)),
                ("latitude", models.FloatField(db_index=True, null=True)),
                ("autonomous_system_organization", models.TextField(null=True)),
                ("country_name", models.TextField(null=True)),
                ("city_name", models.TextField(null=True)),
                ("user", models.TextField(null=True)),
                ("event", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("http_status", models.PositiveIntegerField(null=True)),
                ("user_agent", models.TextField(null=True)),
                ("request_method", models.CharField(max_length=10, null=True)),
                ("content_size", models.PositiveBigIntegerField(null=True)),
                ("is_tor", models.BooleanField(db_index=True)),
                ("ids_score", models.FloatField(db_index=True, default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="http_logs.service",
                    ),
                ),
            ],
        ),
    ]
