version: "3"

services:
  nano_siem:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    environment:
      - MYSQL_DB_NAME=NanoSiem
      - MYSQL_USER=NanoSiem
      - MYSQL_PASSWORD=AIeZ1C7HlC0D3NrbFtsCTGWcUfxNh4
      - MYSQL_HOST=nano_siem_db
      - PLUGINS_LOG_LEVEL=DEBUG
    ports:
      - 127.0.0.1:8000:8000

  nano_siem_db:
    image: mariadb:10.10
    volumes:
      - $PWD/web_service.sql:/docker-entrypoint-initdb.d/web_service.sql
      - $PWD/web_servicelog.sql:/docker-entrypoint-initdb.d/web_servicelog.sql
    environment:
      - MARIADB_USER=NanoSiem
      - MARIADB_DATABASE=NanoSiem
      - MARIADB_PASSWORD=AIeZ1C7HlC0D3NrbFtsCTGWcUfxNh4
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
