# Generated by Django 4.1.3 on 2023-02-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiskService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("type", models.CharField(db_index=True, max_length=10)),
                ("device", models.TextField()),
                ("mount_point", models.TextField()),
                ("uuid", models.TextField(null=True)),
                ("available", models.BooleanField(default=True)),
                ("notified", models.BooleanField(default=False)),
                ("modification_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="NetworkService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("type", models.CharField(db_index=True, max_length=10)),
                ("host", models.TextField(default="")),
                ("port", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                ("notified", models.BooleanField(default=False)),
                ("modification_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="NetworkServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("latency", models.FloatField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="overwatch.networkservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiskServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("available", models.BooleanField()),
                ("free_space", models.BigIntegerField(default=0)),
                ("used_space", models.BigIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="overwatch.diskservice",
                    ),
                ),
            ],
        ),
    ]
