# Generated by Django 4.2.7 on 2023-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overwatch", "0002_remove_networkservice_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diskservice",
            name="available",
        ),
        migrations.AddField(
            model_name="diskservice",
            name="last_available",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
